[workspace]

members = [
    "problem_01",
    "problem_02",
    "problem_03",
    "problem_04",
    "problem_05",
    "problem_06",
    "problem_07",
    "problem_08",
    "problem_09",
    "problem_10",
    "problem_11",
    "problem_12"
]
